### ISSUE TITLE
Can not start server

### ISSUE THREAD

**Issue by mifo123** [amarezenebe/django_calculator#1]
ModuleNotFoundError: No module named 'django_user_agents'

**Comment by amarezenebe** [comment]
sorry  that is because of i forget to remove the  'django_user_agents.middleware.UserAgentMiddleware', middleware from the setting after i debug the project, by removing  this middleware you can solve the problem or colon the project again.
 

MIDDLEWARE=[

    'django_user_agents.middleware.UserAgentMiddleware',

]

**Comment by amarezenebe** [comment]
sorry  that is because of i forget to remove the  'django_user_agents.middleware.UserAgentMiddleware', middleware from the setting after i debug the project, by removing  this middleware you can solve the problem or colon the project again.
 

MIDDLEWARE=[

    'django_user_agents.middleware.UserAgentMiddleware',

]
